### ISSUE TITLE
Can I use sqlite？

### ISSUE THREAD

**Issue by hoslo** [cunarist/rinf#133]
sqlite is not working

```rust
use tokio::sync::OnceCell;

const DB_URL: &str = "sqlite::memory:";

static POOL: OnceCell<Pool<Sqlite>> = OnceCell::const_new();

async fn get_global_db<'a>() -> &'a Pool<Sqlite> {
    POOL.get_or_init(|| async {
        SqlitePoolOptions::new()
.connect(DB_URL).await.unwrap()
    }).await
}


async fn main() {   
    let mut request_receiver = bridge::get_request_receiver();
    // It looks like the function is blocking here
    get_global_db().await;
    

    while let Some(request_unique) = request_receiver.recv().await {
        crate::spawn(async {
            let response_unique = handle_request(request_unique).await;
            respond_to_dart(response_unique);
        });
    }
}
```

**Comment by temeddix** [comment]
Yeah, it should possible to use `sqlite` as well as any Rust crates. I wonder why it's blocking at that point, isn't there any panic going on at `unwrap()`?

**Comment by hoslo** [comment]
> Yeah, it should possible to use `sqlite` as well as any Rust crates. I wonder why it's blocking at that point, isn't there any panic going on at `unwrap()`?

It is possible to use sqlite in memory, but not if you use files
```rust
const DB_URL: &str = "sqlite:test.db";
```

**Comment by temeddix** [comment]
That's strange. It should just work as well as all other Rust crates. I'll take a look later when I have time :|

**Comment by temeddix** [comment]
Hmm, this doesn't look like an issue with RIF.

Could you try these and tell me if the problem persists?
- https://stackoverflow.com/questions/72763578/how-to-create-a-sqlite-database-with-rust-sqlx
- https://github.com/launchbadge/sqlx/issues/1114

P.S. File operations won't work if you run or build the app for the web.

**Comment by hoslo** [comment]
> Hmm, this doesn't look like an issue with RIF.
> 
> Could you try these and tell me if the problem persists?
> 
> * https://stackoverflow.com/questions/72763578/how-to-create-a-sqlite-database-with-rust-sqlx
> * [How to create the SQLite database on application startup if it does not already exist? launchbadge/sqlx#1114](https://github.com/launchbadge/sqlx/issues/1114)
> 
> P.S. File operations won't work if you run or build the app for the web.

The above two methods can automatically create sqlite files in rust binary programs, but flutter can not, I'm not sure if trying rust in flutter can we manipulate files directly in rust code (native)?

**Comment by temeddix** [comment]
If I understood correctly, that those two methods can automatically create sqlite files in 'Application folder', is this right? Or is it that `sqlite` files are embeeded in `.dll`, `.a`, `.so` binary files?

Could you provide some more information like...:
- Which OS are you developing on?
- Which OS are you targeting?
- Do you have error messages from the CLI?
- Is it some kind of permission problem?

**Comment by hoslo** [comment]
> If I understood correctly, that those two methods can automatically create sqlite files in 'Application folder', is this right? Or is it that `sqlite` files are embeeded in `.dll`, `.a`, `.so` binary files?
> 
> Could you provide some more information like...:
> 
> * Which OS are you developing on?
> * Which OS are you targeting?
> * Do you have error messages from the CLI?
> * Is it some kind of permission problem?

I'm developing on macos (m1 chip), targeting the iphone emulator, and I don't see task error messages from the cli, except that each request fails after a timeout

**Comment by temeddix** [comment]
I see 🤔 do you mind showing me your code, perhaps by sharing your repository address?

One of the reasons could be the app sandbox policy of iOS. Can you try running your app on macOS and share the result?

**Comment by hoslo** [comment]
> I see 🤔 do you mind showing me your code, perhaps by sharing your repository address?
> 
> One of the reasons could be the app sandbox policy of iOS. Can you try running your app on macOS and share the result?

you can look at this repo https://github.com/hoslo/tally

**Comment by LucaCoduriV** [comment]
Same for me, I am trying to use SurrealDB embedded in my rust code. But the app wont compile using file but compiles with memory. 

```bash
flutter run -v               
[  +21 ms] executing: uname -m
[   +9 ms] Exit code 0 from: uname -m
[        ] x86_64
[  +91 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping
update.
[   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[   +9 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping
update.
[ +111 ms] executing: /home/luca/Android/Sdk/platform-tools/adb devices -l
[  +27 ms] List of devices attached
[   +8 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping
update.
[  +38 ms] Changing current working directory to:
/home/luca/dev/Notiflut-Land/notiflut_daemon
[ +110 ms] Skipping pub get: version match.
[  +47 ms] Found plugin window_manager at
/home/luca/.pub-cache/git/window_manager-6f627e825db10d2f45bef0e0bbabdf5d1ecf1cb3/
[  +81 ms] Found plugin rust_in_flutter at
/home/luca/.pub-cache/hosted/pub.dev/rust_in_flutter-4.1.4/
[   +6 ms] Found plugin screen_retriever at
/home/luca/.pub-cache/hosted/pub.dev/screen_retriever-0.1.9/
[  +56 ms] Found plugin window_manager at
/home/luca/.pub-cache/git/window_manager-6f627e825db10d2f45bef0e0bbabdf5d1ecf1cb3/
[  +40 ms] Found plugin rust_in_flutter at
/home/luca/.pub-cache/hosted/pub.dev/rust_in_flutter-4.1.4/
[   +3 ms] Found plugin screen_retriever at
/home/luca/.pub-cache/hosted/pub.dev/screen_retriever-0.1.9/
[ +189 ms] Initializing file store
[  +14 ms] Skipping target: gen_localizations
[   +7 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged:
The following inputs have updated contents:
/home/luca/dev/Notiflut-Land/notiflut_daemon/.dart_tool/package_config_subset}
[  +23 ms] Found plugin window_manager at
/home/luca/.pub-cache/git/window_manager-6f627e825db10d2f45bef0e0bbabdf5d1ecf1cb3/
[  +28 ms] Found plugin rust_in_flutter at
/home/luca/.pub-cache/hosted/pub.dev/rust_in_flutter-4.1.4/
[   +1 ms] Found plugin screen_retriever at
/home/luca/.pub-cache/hosted/pub.dev/screen_retriever-0.1.9/
[  +12 ms] gen_dart_plugin_registrant: Complete
[   +1 ms] Skipping target: _composite
[   +3 ms] complete
[   +8 ms] Launching lib/main.dart on Linux in debug mode...
[   +6 ms] /home/luca/.local/share/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/luca/.local/share/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.snapsh
ot --sdk-root
/home/luca/.local/share/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/
--incremental --target=flutter --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true
-DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/bd986c5ed20a62dc34b771
8c50abc782beae4c33/ --output-dill /tmp/flutter_tools.RCWHKG/flutter_tool.WFRCXE/app.dill
--packages /home/luca/dev/Notiflut-Land/notiflut_daemon/.dart_tool/package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation
--filesystem-scheme org-dartlang-root --initialize-from-dill
build/3c6e5cf9bd2369c57f1061727dea4d2d.cache.dill.track.dill --verbosity=error
--enable-experiment=alternative-invalidation-strategy
[  +31 ms] Building Linux application...
[  +21 ms] <- compile package:notiflutland/main.dart
[   +6 ms] executing: [build/linux/x64/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug
-DFLUTTER_TARGET_PLATFORM=linux-x64 /home/luca/dev/Notiflut-Land/notiflut_daemon/linux
[  +64 ms] -- Configuring done (0.0s)
[  +77 ms] -- Generating done (0.0s)
[        ] -- Build files have been written to:
/home/luca/dev/Notiflut-Land/notiflut_daemon/build/linux/x64/debug
[   +4 ms] executing: ninja -C build/linux/x64/debug install
[  +16 ms] ninja: Entering directory `build/linux/x64/debug'
[ +277 ms] [1/10] Generating libhub.so, _phony_
[  +10 ms] FAILED: plugins/rust_in_flutter/libhub.so plugins/rust_in_flutter/_phony_
/home/luca/dev/Notiflut-Land/notiflut_daemon/build/linux/x64/debug/plugins/rust_in_flutter/l
ibhub.so
/home/luca/dev/Notiflut-Land/notiflut_daemon/build/linux/x64/debug/plugins/rust_in_flutter/_
phony_
[  +57 ms] cd
/home/luca/dev/Notiflut-Land/notiflut_daemon/build/linux/x64/debug/plugins/rust_in_flutter
&& /usr/bin/cmake -E env CARGOKIT_CMAKE=/usr/bin/cmake CARGOKIT_CONFIGURATION=Debug
CARGOKIT_MANIFEST_DIR=/home/luca/dev/Notiflut-Land/notiflut_daemon/linux/../native/hub
CARGOKIT_TARGET_TEMP_DIR=/home/luca/dev/Notiflut-Land/notiflut_daemon/build/linux/x64/debug/
plugins/rust_in_flutter/cargokit_build
CARGOKIT_OUTPUT_DIR=/home/luca/dev/Notiflut-Land/notiflut_daemon/build/linux/x64/debug/plugi
ns/rust_in_flutter CARGOKIT_TARGET_PLATFORM=linux-x64
CARGOKIT_TOOL_TEMP_DIR=/home/luca/dev/Notiflut-Land/notiflut_daemon/build/linux/x64/debug/pl
ugins/rust_in_flutter/cargokit_build/tool
CARGOKIT_ROOT_PROJECT_DIR=/home/luca/dev/Notiflut-Land/notiflut_daemon/linux
/home/luca/.pub-cache/hosted/pub.dev/rust_in_flutter-4.1.4/cargokit/run_build_tool.sh
build-cmake
[   +7 ms] Can't load Kernel binary: Invalid SDK hash.
[+4997 ms] [2/10] Generating
/home/luca/dev/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/libflutter_linux_gtk.so
,
/home/luca/dev/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/flutter_linux/fl_basic_
message_channel.h,
/home/luca/dev/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/flutter_linux/fl_binary
_codec.h,
/home/luca/dev/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/flutter_linux/fl_binary
_messenger.h,
/home/luca/dev/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/flutter_linux/fl_dart_p
roject.h,
/home/luca/dev/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/flutter_linux/fl_engine
.h,
/home/luca/dev/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/flutter_linux/fl_json_m
essage_codec.h,
/home/luca/dev/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/flutter_linux/fl_json_m
ethod_codec.h,
/home/luca/dev/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/flutter_linux/fl_messag
e_codec.h,
/home/luca/dev/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/flutter_linux/fl_method
_call.h,
/home/luca/dev/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/flutter_linux/fl_method
_channel.h,
/home/luca/dev/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/flutter_linux/fl_method
_codec.h,
/home/luca/dev/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/flutter_linux/fl_method
_response.h,
/home/luca/dev/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/flutter_linux/fl_plugin
_registrar.h,
/home/luca/dev/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/flutter_linux/fl_plugin
_registry.h,
/home/luca/dev/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/flutter_linux/fl_standa
rd_message_codec.h,
/home/luca/dev/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/flutter_linux/fl_standa
rd_method_codec.h,
/home/luca/dev/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/flutter_linux/fl_string
_codec.h,
/home/luca/dev/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/flutter_linux/fl_value.
h,
/home/luca/dev/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/flutter_linux/fl_view.h
,
/home/luca/dev/Notiflut-Land/notiflut_daemon/linux/flutter/ephemeral/flutter_linux/flutter_l
inux.h, _phony_
[   +6 ms] [  +29 ms] executing: uname -m
[        ] [  +14 ms] Exit code 0 from: uname -m
[        ] [        ] x86_64
[        ] [  +57 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required,
skipping update.
[        ] [   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[        ] [ +192 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] [   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping
update.
[        ] [  +75 ms] Initializing file store
[        ] [  +29 ms] Done initializing file store
[        ] [ +105 ms] Skipping target: gen_localizations
[        ] [  +24 ms] Skipping target: gen_dart_plugin_registrant
[        ] [+1356 ms] Skipping target: unpack_linux
[        ] [+1302 ms] Skipping target: kernel_snapshot
[        ] [ +884 ms] Skipping target: debug_bundle_linux-x64_assets
[        ] [   +1 ms] Persisting file store
[        ] [  +42 ms] Done persisting file store
[        ] [  +41 ms] build succeeded.
[        ] [  +26 ms] "flutter assemble" took 4,090ms.
[        ] [ +302 ms] ensureAnalyticsSent: 276ms
[        ] [        ] Running 0 shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [   +1 ms] exiting with code 0
[   +2 ms] ninja: build stopped: subcommand failed.
[  +24 ms] Building Linux application... (completed in 5.6s)
[+20053 ms] Exception: Build process failed
[   +7 ms] "flutter run" took 26,586ms.
[   +5 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:760:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure>
           (package:flutter_tools/runner.dart:115:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[ +140 ms] ensureAnalyticsSent: 131ms
[        ] Running 1 shutdown hook
[   +7 ms] Shutdown hooks complete
[        ] exiting with code 1
```

**Comment by temeddix** [comment]
Sorry to say this, but I might be busy for a while, so if you happen to find a solution, please share the idea here or in a new pull request. If I become free again, I will dive into this soon. Thank you for your patience :)

**Comment by temeddix** [comment]
<img width="1319" alt="image" src="https://github.com/cunarist/rust-in-flutter/assets/66480156/3de22b2a-9209-41ef-88a6-8021f7f86bf3">

It does work on Windows, other platforms coming soon

**Comment by temeddix** [comment]
<img width="912" alt="image" src="https://github.com/cunarist/rust-in-flutter/assets/66480156/b49a6b68-9feb-4b2b-b314-919d0f00ba6b">

It also runs well on macOS

**Comment by temeddix** [comment]
This was an interesting issue, though it wasn't related to RIF.

Now I understand why it was not working on iOS. The Rust thread `panic`ked because you didn't have the permission to store `test.db` beside the executable binary. In iOS, you are only allowed to access specific folders of the app itself. Also, you didn't add `?mode=wrc` to the end of the sqlite path to create one if not present.

To understand what sandboxing is in iOS apps, take a look at this post:
- https://stackoverflow.com/questions/12055990/what-is-sandbox-in-ios-can-i-transfer-data-between-one-app-to-another-app

I was able to fix your app to make it work on iOS. Take a look at my fork:
https://github.com/hoslo/tally/compare/master...temeddix:tally:master
