### ISSUE TITLE
Error when returns a big array

### ISSUE THREAD

**Issue by cathino** [cunarist/rinf#144]
## Report

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly
in the middle of a field. This could either mean that the input
has been truncated or that an embedded message misreported its
own length.

Note that the buffer containing the message has 67544120 bytes, but
CodedBufferReader was allowed to parse only 67108864 bytes.

#0      CodedBufferReader._throwTruncatedMessageError (package:protobuf/src/protobuf/coded_buffer_reader.dart:34:7)
#1      CodedBufferReader._withLimit (package:protobuf/src/protobuf/coded_buffer_reader.dart:57:7)
#2      _readPackableToList (package:protobuf/src/protobuf/coded_buffer.dart:241:11)
#3      _readPackable (package:protobuf/src/protobuf/coded_buffer.dart:205:3)
#4      _mergeFromCodedBufferReader (package:protobuf/src/protobuf/coded_buffer.dart:140:9)
#5      GeneratedMessage.mergeFromBuffer (package:protobuf/src/protobuf/generated_message.dart:192:5)
#6      new ReadResponse.fromBuffer (package:xxx/messages/xxx.pb.dart:89:130)
#7      _HomeSimpleState.build.<anonymous closure> (package:xxx/main.dart:235:64)
<asynchronous suspension>
```

This error is caused when the function returns a big array, and it's OK if the array size is small.
Is there any way to change the `limit of CodedBufferReader`?

## System Information

```bash
rustc --version
rustc 1.72.0 (5680fa18f 2023-08-23)

protoc --version
libprotoc 24.2

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.3, on Microsoft Windows [version 10.0.22621.2283])
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.3)
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.82.1)
[√] Connected device (3 available)
```

**Comment by cathino** [comment]
I found [a post sayes CodedBufferReader constructor takes an optional sizeLimit argument.](https://github.com/google/protobuf.dart/issues/449#issuecomment-1097937876)

Could I do this via `rust-in-flutter` config?

Thank you.

**Comment by temeddix** [comment]
Will inspect this soon, thanks for the report :)

**Comment by temeddix** [comment]
May I ask you if you're using one of the fields of the protobuf message as binary, with a large size?

**Comment by cathino** [comment]
@temeddix 

My proto like:

```
message ReadResponse {
  repeated float output_numbers = 1;
  string output_string = 2;
}
```

`output_numbers`  is an array of f32 type of rust, and it can be very big.

When the length of output_numbers is 16886016, it will cause the error I posted.

After I made a small slice :
```rust
output_numbers = rrr[0..16000000].to_vec()
```

It works.

This slice didn't work:

```rust
output_numbers = rrr[0..16880000].to_vec()
```

**Comment by cathino** [comment]
I decided to modify my logic and use a simple array to solve this issue.

**Comment by temeddix** [comment]
I see. I will look into how I can remove that limitation for good.

**Comment by temeddix** [comment]
Version 4.0.0 solves this issue, try out the new `blob` field :)

https://docs.cunarist.com/rust-in-flutter/writing-code/#field-blob
