### ISSUE TITLE
cargokit build failed

### ISSUE THREAD

**Issue by faimin** [cunarist/rinf#167]
## Report

compile error

```shell
SEVERE: ================================================================================
SEVERE: Cargokit BuildTool failed with error:
SEVERE: --------------------------------------------------------------------------------
SEVERE: PathNotFoundException: Cannot open file, path = '/Users/zero.d.saber/Documents/Dev/Github/ZDAgeFans/zd_age_fans/macos/Pods/../../native/hub/Cargo.toml' (OS Error: No such file or directory, errno = 2)
SEVERE: --------------------------------------------------------------------------------
SEVERE: #0      _File.throwIfError (dart:io/file_impl.dart:675:7)

SEVERE: #1      _File.openSync (dart:io/file_impl.dart:490:5)
SEVERE: #2      _File.readAsBytesSync (dart:io/file_impl.dart:574:18)
SEVERE: #3      _File.readAsStringSync (dart:io/file_impl.dart:624:18)

SEVERE: #4      CrateInfo.load (package:build_tool/src/cargo.dart:42:35)
SEVERE: #5      BuildEnvironment.fromEnvironment (package:build_tool/src/builder.dart:89:33)

SEVERE: #6      BuildPod.build (package:build_tool/src/build_pod.dart:28:42)
SEVERE: #7      BuildPodCommand.runBuildCommand (package:build_tool/src/build_tool.dart:48:17)
SEVERE: #8      BuildCommand.run (package:build_tool/src/build_tool.dart:34:11)
SEVERE: #9      CommandRunner.runCommand
command_runner.dart:212
SEVERE: #10     CommandRunner.run.<anonymous closure>
command_runner.dart:122
SEVERE: #11     new Future.sync (dart:async/future.dart:305:31)
SEVERE: #12     CommandRunner.run
SEVERE: #13     runMain (package:build_tool/src/build_tool.dart:248:18)
SEVERE: #14     runMain (package:build_tool/build_tool.dart:4:21)

SEVERE: #15     main
build_tool_runner.dart:3
SEVERE: #16     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:294:33)

SEVERE: #17     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
SEVERE: --------------------------------------------------------------------------------
SEVERE: BuildTool arguments: [build-pod, /Users/zero.d.saber/Documents/Dev/Github/ZDAgeFans/zd_age_fans/macos/Pods/../../native/hub, hub]
SEVERE: ================================================================================
Command PhaseScriptExecution failed with a nonzero exit code
ld: file not found: /Users/zero.d.saber/Documents/Dev/Github/ZDAgeFans/zd_age_fans/build/macos/Build/Products/Debug/rust_in_flutter/libhub.a
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ld: framework not found rust_in_flutter
clang: error: linker command failed with exit code 1 (use -v to see invocation)
** BUILD FAILED **

Exception: Build process failed
Exited
```

## Steps to Reproduce

`flutter run`

develop mac app with vscode

## System Information

ENV: 
- macOS
- vscode
- cocoapods: 1.13.0

```bash
rustc 1.72.1 (d5c2e9c34 2023-09-13)
```

```bash
❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.5, on macOS 13.5.2 22G91 darwin-x64, locale zh-Hans-DZ)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for
      detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.82.2)
[✓] Connected device (3 available)
[✓] Network resources
```

```bash
❯ protoc --version
libprotoc 24.3
```

**Comment by temeddix** [comment]
Hmm that's strange, did you run `rifs template` right at the Flutter app's directory? It looks like you don't have Rust crates present yet in your project.

**Comment by faimin** [comment]
> Hmm that's strange, did you run `rifs template` right at the Flutter app's directory? It looks like you don't have Rust crates present yet in your project.

Sorry, it's my fault. I didn't read [the instructions document](https://docs.cunarist.com/rust-in-flutter/applying-template/) carefully and I lacked some operations. It's OK now after excute `rifs template && rifs message`.

**Comment by temeddix** [comment]
Glad to hear that, good luck with your project! Feel free to come back if you have any other problems :)
