### ISSUE TITLE
Cannot run in non-interactive mode

### ISSUE THREAD

**Issue by istudyatuni** [cunarist/rinf#441]
## Report

When trying to run `rinf message -w` in non-interactive mode (when stdin not available), rinf crashes with error

```
Unhandled exception:
StdinException: Error setting terminal echo mode, OS Error: Inappropriate ioctl for device, errno = 25
#0      Stdin.echoMode= (dart:io-patch/stdio_patch.dart:85:7)
#1      watchAndGenerateMessageCode (file:///home/[...]/.pub-cache/hosted/pub.dev/rinf-6.15.0/bin/src/message.dart:637:9)
#2      main (file:///home/[...]/.pub-cache/hosted/pub.dev/rinf-6.15.0/bin/rinf.dart:25:15)
<asynchronous suspension>
```

## Steps to Reproduce

Create `Makefile`:
```make
.PHONY: watch
watch:
	rinf message -w&disown
```
Run:
```sh
make watch
```

## System Information

_Please provide the output from the command below, using markdown codeblock syntax._

```bash
rustc --version
flutter doctor
```

<details><summary>Details</summary>
<p>

```
rustc 1.81.0 (eeb90cda1 2024-09-04)
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.1, on NixOS 24.05 (Uakari) 6.6.48, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/linux-android-setup for more details.
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (version 2023.2)
    ✗ Unable to determine bundled Java version.
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 2 categories
```

</p>
</details>

**Comment by temeddix** [comment]
Thanks for the report :)

**Comment by istudyatuni** [comment]
Also see https://github.com/flutter/flutter/pull/43225 which fixes similar issue

**Comment by temeddix** [comment]
From Rinf version 8, the `rinf gen` mechanism has completely changed. That's why we're closing this as "invalid", but feel free to continue the discussion if needed.
